name: Dependabot Auto Merge

on: pull_request

jobs:
  merge:
    if: github.event.pull_request.user.type == 'Bot'
    name: Dependabot Auto Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.BOTPR}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@dependabot squash and merge'
            })
